server:
  port: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3001.com:3001/eureka/ #eureka服务端提供的注册地址 参考服务端配置的这个
  instance:
    instance-id: gateway #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示ip地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户端需要多长时间发送心跳给eureka服务器，表明它仍然活着, 默认为30秒（与下面配置的单位都是秒）
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认90秒

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CLIENT-USER
          uri: http://localhost:5000
          predicates:
            - After=2020-08-25T16:41:37.789+8:00
      enabled: true

#  cloud:
#    gateway:
#      routes:
#        - id: CLIENT-USER
#          uri: http://localhost:5000
#          predicates:
#            - Between=2020-01-20T17:42:47.789-07:00[America/Denver], 2021-01-21T17:42:47.789-07:00[America/Denver]