server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka/ #eureka服务端提供的注册地址 参考服务端配置的这个
  instance:
    instance-id: zuul-0 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示ip地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户端需要多长时间发送心跳给eureka服务器，表明它仍然活着, 默认为30秒（与下面配置的单位都是秒）
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认90秒

spring:
  application:
    name: zuul #此实例注册到eureka服务端的name

zuul:
  routes:
    power:
      serviceId: zuul-server
      path: /zuul/**
  ignored-services: zuul-server
  prefix: /api
#  strip-prefix: false  #是否跳过前缀名