server:
  port: 3002
eureka:
  server:
      enable-self-preservation: true #关闭自我保护机制
      eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位: 毫秒 默认值是60*1000 一分钟）
  instance:
    hostname: eureka3002.com

  client:
    registerWithEureka: true #不要把自己作为一个客户端注册到自己身上
    fetchRegistry: true #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己的注册了）
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka

spring:
  application:
    name: eureka-service #此实例注册到eureka服务端的name